// Shared engine types.

import type { Product } from './products';

export type DiscountKind = 'shop' | 'product' | 'bargain';

export type Discount = {
  kind: DiscountKind;
  percent: number;            // e.g. 10 for 10%
  appliesTo: 'all' | 'single';
  productIndex?: number;      // when appliesTo === 'single'
};

export type OrderLine = {
  product: Product;
  quantity: number;   // whole packs
  units: number;      // loose units from a pack (partial quantity)
};

export type CustomerKind =
  | 'patient' | 'impatient' | 'confused' | 'talkative' | 'big'
  | 'exact' | 'large-note' | 'bargainer' | 'fast' | 'elderly' | 'distracting';

export type CustomerSpec = {
  id: number;
  kind: CustomerKind;
  name: string;
  dialogue: string[];
  patienceMs: number;
  speaksFast: boolean;
};

export type LineBreakdown = {
  product: Product;
  quantity: number;
  units: number;
  mrp: number;
  unitPrice: number | null;
  gross: number;          // paise, before discount
  discountPct: number;    // applied percent for this line
  discountAmt: number;    // paise
  net: number;            // paise
};

export type TransactionSpec = {
  id: number;
  lines: OrderLine[];
  discounts: Discount[];
  customer: CustomerSpec;
  // generated by engine:
  bill: Bill;
  payment: PaymentSpec;
};

export type Bill = {
  lines: LineBreakdown[];
  subtotal: number;      // paise, gross
  totalDiscount: number; // paise
  total: number;         // paise
};

export type PaymentSpec = {
  given: Record<string, number>; // denom id -> count (what the customer hands over)
  amount: number;                // paise
  change: number;                // paise
  changeCounts: Record<string, number>; // optimal change combination
};

export type DiffCategory =
  | 'mrp-reading'
  | 'quantity'
  | 'multiplication'
  | 'division'
  | 'discount'
  | 'addition'
  | 'subtraction'
  | 'payment-recognition'
  | 'change-calculation'
  | 'wrong-denomination'
  | 'forgot-discount'
  | 'discount-twice'
  | 'wrong-product'
  | 'forgot-partial'
  | 'calculator-entry'
  | 'too-slow'
  | 'none';

export type DiffReport = {
  billCorrect: boolean;
  changeCorrect: boolean;
  denominationsCorrect: boolean;
  categories: DiffCategory[];
};
